
title: "FrankE Projects"
description: "Portfolio site showcasing projects with Python, SQL, Power BI, and more."
theme:theme: jekyll-theme-primer
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
exclude:
  - Gemfile

